import numpy as np
mark=np.array([10,80,55,62,30])
print("mark is:",mark)
print("highest mark is:",mark.max())
print("lowest mark is:",mark.min())
print("Avg mark is:",mark.mean())
print("total mark is:",mark.sum())
mark=np.append(mark,[12,40,88,66,100])
print("updated mark is:",mark)
print("highest mark is:",mark.max())
print("lowest mark is:",mark.min())
print("Avg mark is:",mark.mean())
print("total mark is:",mark.sum())
print("mark with grace is :", mark + 5 )